### ISSUE TITLE
[BUG] Conflicting meta description tags on feature guide pages

### ISSUE THREAD

**Issue by nbeck415** [ephemeralenvironments/ephemeralenvironments#43]
**Describe the bug**

On feature guide pages, if you inspect the meta tags, there will be two description properties with *different* descs:
1. the site's general meta desc
2. the page's specific meta desc

**To Reproduce**
1. Go to https://ephemeralenvironments.io/features/collaboration/ (e.g.)
2. Inspect page
3. Look at html head + meta tags

**Expected behavior**

Only display the page's specific meta desc (the one specified by each .md file). This way, search engines will know which one to correctly assign to each page

**Assign to self**

- [ ] I would like to work on this issue

**Comment by creaturenex** [comment]
I would like to take this on :)

**Comment by nbeck415** [comment]
Awesome, will assign to you @creaturenex

**Comment by creaturenex** [comment]
Hey @nbeck415 

Just to confirm these are the conflicting tags?
`<meta name="description" content="Use ephemeral environments simplify to many of the barriers that plague cross-team communications, resulting in a faster, smoother workflow">`

`<meta name="og:description" content="Use ephemeral environments simplify to many of the barriers that plague cross-team communications, resulting in a faster, smoother workflow">`

`<meta name="og:description" content="Learn how ephemeral environments can help you and your team">`

**Comment by nbeck415** [comment]
@creaturenex it looks like in meta.html the tags are determined by [Hugo's conditionals](https://gohugo.io/templates/introduction/#conditionals) in the meta.html file that handle for different YAML configurations, and at first glance you might be able to port any unreferenced tags from index.html over. I believe any meta vars set for the homepage in config.toml should get picked up. Then you could just use the meta.html partial in index.html. But again I need to double check this

As for the third conflicting tag, you can probably just delete it from meta.html. The duplicate tags are *probably* fine, but would love to hear your opinion on this, if you're familiar with how the browser handles "description" vs "og:description"

**Comment by creaturenex** [comment]
Your comments make sense but will have digest the documentation and test if that is what is actually going on. My surface level inspection shows that the content pages ie `https://ephemeralenvironments.io/features/collaboration/` meta tags overwrite the index meta tags(by using Hugo conditionals). Pretty sure the site is working as intended, besides the duplicate which I think solution below will solve.

I will delete the third meta tag from the meta.html under partial as that seems to remove the conflicting meta description.

Also because this third meta tags is in the partial it affects all the content pages not just collaboration. WIth it removed all .md will reference the correct description

As for duplicate description vs og:description. I will keep both as my understanding is that it is a difference if how the site is presented via social media using open graph vs non social media site. 
![Screenshot (2)](https://github.com/ephemeralenvironments/ephemeralenvironments/assets/15052690/04c107a5-7fff-4ebd-ac25-245dd11f08d6)
